from typing import Literal
item_types = Literal[
    "Abyssal Mask",
    "Adaptive Helm",
    "Aegis of the Legion",
    "Aether Wisp",
    "Amplifying Tome",
    "Anathema's Chains",
    "Archangel's Staff",
    "Ardent Censer",
    "Armored Advance",
    "Axiom Arc",
    "B. F. Sword",
    "Bami's Cinder",
    "Bandleglass Mirror",
    "Banshee's Veil",
    "Berserker's Greaves",
    "Black Cleaver",
    "Blackfire Torch",
    "Blade of The Ruined King",
    "Blasting Wand",
    "Blighting Jewel",
    "Bloodsong",
    "Bloodthirster",
    "Boots",
    "Boots of Swiftness",
    "Bounty of Worlds",
    "Bramble Vest",
    "Catalyst of Aeons",
    "Caulfield's Warhammer",
    "Celestial Opposition",
    "Chain Vest",
    "Chainlaced Crushers",
    "Chempunk Chainsword",
    "Cloak of Agility",
    "Cloth Armor",
    "Control Ward",
    "Cosmic Drive",
    "Cryptbloom",
    "Cull",
    "Dagger",
    "Dark Seal",
    "Darksteel Talons",
    "Dawncore",
    "Dead Man's Plate",
    "Death's Dance",
    "Demonic Embrace",
    "Divine Sunderer",
    "Doran's Blade",
    "Doran's Ring",
    "Doran's Shield",
    "Dream Maker",
    "Echoes of Helia",
    "Eclipse",
    "Edge of Night",
    "Eleisa's Miracle",
    "Elixir of Avarice",
    "Elixir of Force",
    "Elixir of Iron",
    "Elixir of Skill",
    "Elixir of Sorcery",
    "Elixir of Wrath",
    "Essence Reaver",
    "Experimental Hexplate",
    "Eye of the Herald",
    "Faerie Charm",
    "Farsight Alteration",
    "Fated Ashes",
    "Fiendish Codex",
    "Fimbulwinter",
    "Forbidden Idol",
    "Force of Nature",
    "Frozen Heart",
    "Gargoyle Stoneplate",
    "Giant's Belt",
    "Glowing Mote",
    "Guardian Angel",
    "Guinsoo's Rageblade",
    "Gustwalker Hatchling",
    "Haunting Guise",
    "Health Potion",
    "Hearthbound Axe",
    "Heartsteel",
    "Hellfire Hatchet",
    "Hexdrinker",
    "Hextech Alternator",
    "Hextech Gunblade",
    "Hextech Rocketbelt",
    "Hollow Radiance",
    "Horizon Focus",
    "Hubris",
    "Hullbreaker",
    "Iceborn Gauntlet",
    "Immortal Shieldbow",
    "Imperial Mandate",
    "Infinity Edge",
    "Ionian Boots of Lucidity",
    "Jak'Sho, The Protean",
    "Kaenic Rookern",
    "Kindlegem",
    "Knight's Vow",
    "Kraken Slayer",
    "Last Whisper",
    "Liandry's Torment",
    "Lich Bane",
    "Locket of the Iron Solari",
    "Long Sword",
    "Lord Dominik's Regards",
    "Lost Chapter",
    "Luden's Companion",
    "Malignance",
    "Manamune",
    "Maw of Malmortius",
    "Mejai's Soulstealer",
    "Mercurial Scimitar",
    "Mercury's Treads",
    "Mikael's Blessing",
    "Moonstone Renewer",
    "Morellonomicon",
    "Mortal Reminder",
    "Mosstomper Seedling",
    "Muramana",
    "Nashor's Tooth",
    "Navori Flickerblade",
    "Needlessly Large Rod",
    "Negatron Cloak",
    "Noonquiver",
    "Null-Magic Mantle",
    "Oblivion Orb",
    "Opportunity",
    "Oracle Lens",
    "Overlord's Bloodmail",
    "Phage",
    "Phantom Dancer",
    "Pickaxe",
    "Plated Steelcaps",
    "Profane Hydra",
    "Quicksilver Sash",
    "Rabadon's Deathcap",
    "Randuin's Omen",
    "Rapid Firecannon",
    "Ravenous Hydra",
    "Rectrix",
    "Recurve Bow",
    "Redemption",
    "Refillable Potion",
    "Rejuvenation Bead",
    "Riftmaker",
    "Rod of Ages",
    "Ruby Crystal",
    "Runaan's Hurricane",
    "Runic Compass",
    "Rylai's Crystal Scepter",
    "Sapphire Crystal",
    "Scarecrow Effigy",
    "Scorchclaw Pup",
    "Scout's Slingshot",
    "Seeker's Armguard",
    "Seraph's Embrace",
    "Serpent's Fang",
    "Serrated Dirk",
    "Serylda's Grudge",
    "Shadowflame",
    "Shattered Armguard",
    "Sheen",
    "Shurelya's Battlesong",
    "Silvermere Dawn",
    "Slightly Magical Footwear",
    "Solstice Sleigh",
    "Sorcerer's Shoes",
    "Spear of Shojin",
    "Spellslinger's Shoes",
    "Spirit Visage",
    "Staff of Flowing Water",
    "Statikk Shiv",
    "Stealth Ward",
    "Steel Sigil",
    "Sterak's Gage",
    "Stormsurge",
    "Stridebreaker",
    "Sundered Sky",
    "Sunfire Aegis",
    "Symbiotic Soles",
    "Synchronized Souls",
    "Tear of the Goddess",
    "Terminus",
    "The Brutalizer",
    "The Collector",
    "Thornmail",
    "Tiamat",
    "Titanic Hydra",
    "Total Biscuit of Everlasting Will",
    "Trailblazer",
    "Trinity Force",
    "Tunneler",
    "Umbral Glaive",
    "Unending Despair",
    "Vampiric Scepter",
    "Verdant Barrier",
    "Vigilant Wardstone",
    "Void Staff",
    "Voltaic Cyclosword",
    "Warden's Mail",
    "Warmog's Armor",
    "Watchful Wardstone",
    "Winged Moonplate",
    "Winter's Approach",
    "Wit's End",
    "World Atlas",
    "Youmuu's Ghostblade",
    "Your Cut",
    "Yun Tal Wildarrows",
    "Zaz'Zak's Realmspike",
    "Zeal",
    "Zeke's Convergence",
    "Zhonya's Hourglass"
]